import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/Providers/AuthProvider"; 
import { ToastContainer } from "react-toastify"; 
import { WorkspaceProvider } from "@/Providers/WorkspaceProvider";
import { BoardProvider } from "@/Providers/BoardProvider";
import { QueryProvider } from "@/Providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <AuthProvider>
            <WorkspaceProvider>
              <BoardProvider>{children}</BoardProvider>
            </WorkspaceProvider>
          </AuthProvider>
        </QueryProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
