import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/Providers/AuthProvider";
import Navbar from "@/components/widgets/Navbar";
import { ToastContainer } from "react-toastify";
import WorkspaceSidebar from "@/components/features/workspace/WorkspaceSidebar";
import { WorkspaceProvider } from "@/Providers/WorkspaceProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <WorkspaceProvider>
            <div className="flex flex-col w-full h-screen">
              <Navbar />
              <main className="flex h-screen">
                <WorkspaceSidebar />
                <div className="flex-1 p-4">{children}</div>
              </main>
            </div>
          </WorkspaceProvider>
        </AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
